basePath: /api/v1
definitions:
  db.Account:
    properties:
      balance:
        type: integer
      created_at:
        type: string
      currency:
        type: string
      id:
        type: integer
      owner:
        type: string
    type: object
  dto.AccountListResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/db.Account'
        type: array
      total_data:
        type: integer
    type: object
  dto.CreateAccountRequest:
    properties:
      currency:
        enum:
        - USD
        - EUR
        type: string
      owner:
        type: string
    required:
    - currency
    - owner
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample API server with authentication
  title: github.com/simple-go-project API
  version: "1.0"
paths:
  /accounts:
    get:
      consumes:
      - application/json
      description: Retrieve multiple accounts with pagination (limit & offset).
      parameters:
      - description: Max number of accounts to return (min=5, max=30)
        in: query
        name: limit
        required: true
        type: integer
      - description: Number of accounts to skip (min=0)
        in: query
        name: offset
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.AccountListResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get list of accounts
      tags:
      - accounts
    post:
      consumes:
      - application/json
      description: Create a new bank account with owner and currency
      parameters:
      - description: Account info
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/dto.CreateAccountRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/db.Account'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create a new account
      tags:
      - accounts
  /accounts/{id}:
    get:
      consumes:
      - application/json
      description: Retrieve account details by account ID
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/db.Account'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get account by ID
      tags:
      - accounts
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
